"""initial shared core and finance schema"""

from alembic import op
import sqlalchemy as sa

revision = "5aba178b468a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contacts",
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_id", sa.String(length=160), nullable=True),
        sa.Column("saved", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("company", sa.String(length=250), nullable=False),
        sa.Column("location", sa.String(length=250), nullable=False),
        sa.Column("school", sa.String(length=250), nullable=False),
        sa.Column("profile_url", sa.Text(), nullable=False),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("email_status", sa.String(length=60), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "provider", "provider_id"),
    )
    op.create_index(
        op.f("ix_contacts_workspace_id"), "contacts", ["workspace_id"], unique=False
    )
    op.create_table(
        "personas",
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("domain", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personas_workspace_id"), "personas", ["workspace_id"], unique=False
    )
    op.create_table(
        "contact_domain_profiles",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("domain", sa.String(length=30), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "contact_id", "domain"),
    )
    op.create_index(
        op.f("ix_contact_domain_profiles_contact_id"),
        "contact_domain_profiles",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_domain_profiles_workspace_id"),
        "contact_domain_profiles",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "drafts",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("persona_id", sa.String(length=36), nullable=True),
        sa.Column("persona_version", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("starting_point", sa.String(length=60), nullable=False),
        sa.Column("tone", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("generation_provider", sa.String(length=30), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drafts_contact_id"), "drafts", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_drafts_workspace_id"), "drafts", ["workspace_id"], unique=False
    )
    op.create_table(
        "persona_revisions",
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "persona_id", "version"),
    )
    op.create_index(
        op.f("ix_persona_revisions_persona_id"),
        "persona_revisions",
        ["persona_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_revisions_workspace_id"),
        "persona_revisions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "source_evidence",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_evidence_contact_id"),
        "source_evidence",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_evidence_workspace_id"),
        "source_evidence",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "uploaded_documents",
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_uploaded_documents_workspace_id"),
        "uploaded_documents",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "match_assessments",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("persona_revision_id", sa.String(length=36), nullable=False),
        sa.Column("persona_version", sa.Integer(), nullable=False),
        sa.Column("contact_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_revision_id"],
            ["persona_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_assessments_contact_id"),
        "match_assessments",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_assessments_workspace_id"),
        "match_assessments",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_match_assessments_workspace_id"), table_name="match_assessments"
    )
    op.drop_index(
        op.f("ix_match_assessments_contact_id"), table_name="match_assessments"
    )
    op.drop_table("match_assessments")
    op.drop_index(
        op.f("ix_uploaded_documents_workspace_id"), table_name="uploaded_documents"
    )
    op.drop_table("uploaded_documents")
    op.drop_index(op.f("ix_source_evidence_workspace_id"), table_name="source_evidence")
    op.drop_index(op.f("ix_source_evidence_contact_id"), table_name="source_evidence")
    op.drop_table("source_evidence")
    op.drop_index(
        op.f("ix_persona_revisions_workspace_id"), table_name="persona_revisions"
    )
    op.drop_index(
        op.f("ix_persona_revisions_persona_id"), table_name="persona_revisions"
    )
    op.drop_table("persona_revisions")
    op.drop_index(op.f("ix_drafts_workspace_id"), table_name="drafts")
    op.drop_index(op.f("ix_drafts_contact_id"), table_name="drafts")
    op.drop_table("drafts")
    op.drop_index(
        op.f("ix_contact_domain_profiles_workspace_id"),
        table_name="contact_domain_profiles",
    )
    op.drop_index(
        op.f("ix_contact_domain_profiles_contact_id"),
        table_name="contact_domain_profiles",
    )
    op.drop_table("contact_domain_profiles")
    op.drop_index(op.f("ix_personas_workspace_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_index(op.f("ix_contacts_workspace_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
